### PR TITLE
Fix the spell missing

### PR DESCRIPTION
**Pull request by NoCtrlZ**
I just added "l".

### CODE REVIEW

**Comment by NoCtrlZ** [comment]
I checked whether `newRequestBock` function is called other modules and found it doesn't be call.

**Comment by lunfardo314** [comment]
it does here: https://github.com/lunfardo314/goshimmer/blob/9b18f79970e0fdc0325155146d37be3f751178a1/plugins/qnode/modelimpl/init.go#L13

**Comment by NoCtrlZ** [comment]
Oh sorry.
It seems I checked the master branch.

**Comment by NoCtrlZ** [comment]
I fixed that.

**Pull request merged**
